### ISSUE TITLE
Please Read if u say that the mod is not working!

### ISSUE THREAD

**Issue by aubree-lat** [Yizzii/YizziCamModV2#35]
Bepinject and Extenject are currently not working and they are needed for the mod to work, use alternatives for now until a fix is released!

**Comment by airnoah67** [comment]
thank you

**Comment by Yizzii** [comment]
this mod doesnt use those but alr

**Comment by aubree-lat** [comment]
oh mb, devs moved camera stuff around so it screwed up some stuff in it.
